on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check and Test Coverage

jobs:
  run-tests:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: '4.3.3'}
          - {os: windows-latest, r: '4.3.3'}

    env:
      RENV_PATHS_ROOT: ~/.cache/R/renv

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "covr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Run test coverage
        run: |
          covr::package_coverage()

